# Generated by Django 6.0.1 on 2026-01-14 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم المركز')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('discription', models.TextField(verbose_name='وصف المركز')),
                ('logo', models.ImageField(blank=True, upload_to='centers/logos/%y/%m', verbose_name='صورة الشعار')),
                ('contact_phone', models.CharField(max_length=15, verbose_name='رقم التواصل')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('state', models.CharField(choices=[('khrtoum', 'الخرطوم'), ('PortSudan', 'بورتسودان'), ('Kasala', 'كسلا')], verbose_name='الولاية')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('latitude', models.FloatField(verbose_name='خط الطول')),
                ('longitude', models.FloatField(verbose_name='خط العرض')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاريخ الإنضمام')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'المركز',
                'verbose_name_plural': 'المراكز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الدورة')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='courses/images/%y/%m', verbose_name='اعلان الدورة')),
                ('short_discription', models.CharField(max_length=300, verbose_name='وصف مختصر')),
                ('learning_outcomes', models.TextField(verbose_name='مخرجات الدورة')),
                ('details', models.TextField(verbose_name='التفاصيل')),
                ('price', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='السعر')),
                ('currency', models.CharField(max_length=20, verbose_name='العملة')),
                ('installment_available', models.BooleanField(default=False, verbose_name='يتوفر التقسيط')),
                ('installment_details', models.TextField(blank=True, verbose_name='تفاصيل التقسيط')),
                ('length', models.CharField(max_length=100, verbose_name='المدة')),
                ('start_date', models.DateField(blank=True, verbose_name='تاريخ البدء')),
                ('schedule', models.TextField(blank=True, verbose_name='الجدول الزمني')),
                ('course_type', models.CharField(choices=[('in_person', 'حضوري'), ('onine', 'أونلاين'), ('hybrid', 'حضوري وأونلاين')], max_length=30, verbose_name='نوع الدورة')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='المكان')),
                ('online_platform', models.CharField(blank=True, max_length=100, verbose_name='المنصة')),
                ('is_active', models.BooleanField(default=True, verbose_name='الدورة نشطة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='الدورة مميزة')),
                ('view_count', models.PositiveIntegerField(verbose_name='عدد المشاهدات')),
                ('leads_count', models.PositiveIntegerField(verbose_name='عدد المهتمين')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.center', verbose_name='المركز')),
            ],
            options={
                'verbose_name': 'الدورة',
                'verbose_name_plural': 'الدورات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('student_phone', models.CharField(max_length=15, verbose_name='رقم التواصل')),
                ('student_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الالكتروني')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.center', verbose_name='المركز')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.course', verbose_name='الدورة')),
            ],
            options={
                'verbose_name': 'الدليل',
                'verbose_name_plural': 'الأدلة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('is_verified', models.BooleanField(default=False, verbose_name='معرف')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.center', verbose_name='المركز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'الملف الشخصي',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.profile', verbose_name='المسؤول'),
        ),
    ]
