# Generated by Django 6.0.1 on 2026-01-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[('SDB', 'جنية سوداني'), ('USD', 'دولار أمريكي'), ('SR', 'ريال سعودي'), ('EGB', 'جنيه مصري')], max_length=20, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='leads_count',
            field=models.PositiveIntegerField(blank=True, verbose_name='عدد المهتمين'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, verbose_name='عدد المشاهدات'),
        ),
    ]
