# Generated by Django 6.0.1 on 2026-01-23 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_currency_alter_course_leads_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'الدورات',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'الدورات',
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='student_phone',
        ),
        migrations.AddField(
            model_name='center',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='center',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='course',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='center',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم التواصل'),
        ),
        migrations.AlterField(
            model_name='center',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='centers/logos/%y/%m', verbose_name='صورة الشعار'),
        ),
        migrations.AlterField(
            model_name='center',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='course',
            name='installment_details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل التقسيط'),
        ),
        migrations.AlterField(
            model_name='course',
            name='leads_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='عدد المهتمين'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.TextField(blank=True, null=True, verbose_name='الجدول الزمني'),
        ),
        migrations.AlterField(
            model_name='course',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='student_email',
            field=models.EmailField(max_length=254, verbose_name='البريد الالكتروني'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='center',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centers', to='core.state', verbose_name='الولاية'),
        ),
        migrations.AddField(
            model_name='center',
            name='subjects',
            field=models.ManyToManyField(related_name='centers', to='core.subject', verbose_name=''),
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(related_name='courses', to='core.subject', verbose_name=''),
        ),
    ]
