# Generated by Django 6.0.1 on 2026-02-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_state_subject_remove_course_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['title'], 'verbose_name': 'الولاية', 'verbose_name_plural': 'الولايات'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title'], 'verbose_name': 'المجال', 'verbose_name_plural': 'المجالات'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='schedule',
        ),
        migrations.AddField(
            model_name='center',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
        migrations.AddField(
            model_name='center',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AlterField(
            model_name='center',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='center',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='معرف'),
        ),
        migrations.AlterField(
            model_name='center',
            name='subjects',
            field=models.ManyToManyField(related_name='centers', to='core.subject', verbose_name='مجالات المركز'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='الدورة معرفة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(related_name='courses', to='core.subject', verbose_name='مجالات الدورة'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='تعليق'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, choices=[('manager', 'مدير'), ('staff', 'موظف')], max_length=100, null=True, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='state',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم الولاية'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم المجال'),
        ),
    ]
