# Generated by Django 6.0.1 on 2026-02-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_state_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='slug',
        ),
    ]
