# Generated by Django 6.0.1 on 2026-02-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_is_verified_remove_profile_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('in_person', 'حضوري'), ('online', 'عن بعد'), ('hybrid', 'حضوري وعن بعد')], max_length=30, verbose_name='نوع الدورة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='السعر'),
        ),
    ]
