# Generated by Django 6.0.1 on 2026-03-04 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_center_is_deleted_alter_course_course_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='student_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.center', verbose_name='المركز'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='تعليق أو س}ال'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكتروني'),
        ),
    ]
