# Generated by Django 6.0.1 on 2026-03-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lead_student_phone_alter_lead_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('course', 'Course Enrollment'), ('center', 'General Center Contact')], default='course', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='تعليق'),
        ),
    ]
