# Generated by Django 6.0.1 on 2026-03-29 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lead_lead_type_alter_lead_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='working_centers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.center', verbose_name='المركز'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.course', verbose_name='الدورة'),
        ),
    ]
