# Generated by Django 6.0.1 on 2026-04-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_center_staff_alter_course_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about_instructor',
            field=models.TextField(blank=True, null=True, verbose_name='نبذة عن المدرب'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_instructor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مدرب الدورة'),
        ),
    ]
