# Generated by Django 6.0.1 on 2026-04-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_course_about_instructor_course_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الشعار'),
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط اعلان الدورة'),
        ),
    ]
