# Generated by Django 6.0.1 on 2026-04-07 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_center_logo_url_course_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='center_type',
            field=models.CharField(choices=[('in_person', 'حضوري'), ('online', 'عن بعد'), ('hybrid', 'حضوري وعن بعد')], default='in_person', max_length=30, verbose_name='نوع المركز'),
        ),
        migrations.AddField(
            model_name='center',
            name='is_individual',
            field=models.BooleanField(default=False, verbose_name='فردي'),
        ),
        migrations.AlterField(
            model_name='center',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='center',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول'),
        ),
        migrations.AlterField(
            model_name='center',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='center',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centers', to='core.state', verbose_name='الولاية'),
        ),
    ]
