# Generated by Django 6.0.1 on 2026-04-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_center_center_type_center_is_individual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'ordering': ['-created_at'], 'permissions': [('can_access_dashboard', 'can_access_dashboard')], 'verbose_name': 'المركز', 'verbose_name_plural': 'المراكز'},
        ),
    ]
