# Generated by Django 6.0.1 on 2026-04-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_center_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='الدورة محذوفة'),
        ),
    ]
