# Generated by Django 6.0.1 on 2026-04-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_course_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(blank=True, choices=[('SDB', 'جنية سوداني'), ('USD', 'دولار أمريكي'), ('SR', 'ريال سعودي'), ('EGB', 'جنيه مصري')], max_length=20, null=True, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='installment_available',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='يتوفر التقسيط'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='السعر'),
        ),
    ]
