# Generated by Django 6.0.1 on 2026-04-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_course_learning_outcomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('source_name', models.CharField(max_length=100)),
                ('target_url', models.URLField()),
                ('click_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
