# Generated by Django 6.0.1 on 2026-05-02 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_trackinglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل معه'), ('closed', 'مغلق')], default='new', max_length=100, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.center', verbose_name='المركز'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
    ]
