# Generated by Django 6.0.1 on 2026-05-09 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_lead_status_lead_updated_at_alter_lead_center_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not_found', 'لم أجد ما ابحث عنه'), ('too_expensive', 'السعر مرتفع'), ('wrong_time', 'وقت الدورة غير مناسب'), ('need_online', 'ارغب بدورةأونلاين'), ('need_offline', 'ارغب بدورة محلية'), ('not_enough_info', 'معلومات الدورة غير كافية'), ('other', 'أخرى')], max_length=20, verbose_name='السبب')),
                ('searched', models.CharField(blank=True, max_length=255, null=True, verbose_name='سجل البحث')),
                ('requested_course', models.CharField(blank=True, max_length=255, verbose_name='الدورة المطلوبة')),
                ('message', models.TextField(blank=True, null=True, verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course', verbose_name='الدورة')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state', verbose_name='مكان الدورة')),
            ],
        ),
    ]
