# Generated by Django 6.0.1 on 2026-05-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_requestcourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestcourse',
            options={'ordering': ['-reason', '-created_at'], 'verbose_name': 'طلب دورة', 'verbose_name_plural': 'طلبات الدورات'},
        ),
    ]
